- jvm/common/src/main/proto/squareup/cash/s2dk/api/alpha/public.proto
Add a protobuf representation of one of the key objects exposed by the s2dk library. This object will be treated as an opaque object for library clients but will provide the foundation for key usage within the s2dk library. In particular the certificate will be used to provide cryptographic keys for encryption and verification in most library operations.
> Port: Add proto container for s2dk Certificate object.

- jvm/common/build.gradle.kts
- jvm/common/src/main/kotlin/app/cash/security_sdk/internal/TinkContentSigner.kt
- jvm/common/src/test/kotlin/app/cash/security_sdk/internal/TinkContentSignerTest.kt
* Add TinkContentSigner to s2dk internal package.
s2dk currently offers certificates as opaque wrappers around x.509 certificates, and uses bouncycastle to manipulate them.  Cash uses the Tink cryptography library, though, for its key management and associated cryptographic operations. s2dk will also likely provide APIs built on top of Tink. Create a TinkContentSigner to enable bouncycastle to work with Tink directly rather than forcing clients to extract keys into a different format prior to calling s2dk.
Internal slack thread:
https://cash.slack.com/archives/C046H8PR3U4/p1668193785853249
JIRA=https://ccp-cashapp.atlassian.net/browse/PRODSQUAD-254
> Port: "Add TinkContentSigner to s2dk internal package."

- jvm/common/src/main/kotlin/app/cash/security_sdk/internal/TinkContentVerifier.kt
- jvm/common/src/test/kotlin/app/cash/security_sdk/internal/TinkContentVerifierTest.kt
TinkContentVerifier is the complement to TinkContentSigner, which allows bouncy castle to verify certificates that were signed by teh TinkContentSigner.  This will be provided by ContentVerifierProvider and passed to the certificate's isSignatureValid() method.
> Port: "Add TinkContentVerifier to s2dk internal utilities."

- jvm/common/src/main/kotlin/app/cash/security_sdk/CertificateUtil.kt
- jvm/common/src/main/kotlin/app/cash/security_sdk/internal/S2DKContentVerifierProvider.kt
- jvm/common/src/main/kotlin/app/cash/security_sdk/internal/TinkContentVerifier.kt
- jvm/common/src/main/kotlin/app/cash/security_sdk/internal/TinkUtil.kt
- jvm/common/src/test/kotlin/app/cash/security_sdk/CertificateUtilTest.kt
- jvm/common/src/test/kotlin/app/cash/security_sdk/internal/S2DKContentVerifierProviderTest.kt
Add createRootSigningCertificate() to CertificateUtil.
This method associates an entity name, validity period and Tink Keyset together into a self-signed certificate which can be used as the root of trust for a certificate chain.
> Port: "Root cert gen"

- jvm/common/src/main/kotlin/app/cash/security_sdk/internal/S2DKContentVerifierProvider.kt
- jvm/common/src/test/kotlin/app/cash/security_sdk/CertificateUtilTest.kt
- jvm/common/src/test/kotlin/app/cash/security_sdk/internal/S2DKContentVerifierProviderTest.kt
This should allow subjectpublickeyinfo extracted from a pkcs10 request to be used directly rather than having to shape it into a temporary certificate object (which is what the request is meant to be used to create).
> Change S2DKContentVerifierProducer to be based on SubjectPublicKeyInfo.

- jvm/common/src/main/kotlin/app/cash/security_sdk/CertificateRequest.kt
- jvm/common/src/main/kotlin/app/cash/security_sdk/CertificateUtil.kt
- jvm/common/src/test/kotlin/app/cash/security_sdk/CertificateUtilTest.kt
Be explicit about pkcs10 certificate request expected as part of a mobile certificate request, and provide a function to create said requests from entity name and Tink keyset.
> Port: "Add createMobileCertReq API and rm subjectInfo() map."

- ios/Example/SecuritySdk.xcodeproj/project.pbxproj
- ios/Example/Tests/DEREncodableTest.swift
- ios/SecuritySdk/Classes/ASN.1/ASN1Type.swift
- ios/SecuritySdk/Classes/ASN.1/DER/DERBitString.swift
- ios/SecuritySdk/Classes/ASN.1/DER/DERBoolean.swift
- ios/SecuritySdk/Classes/ASN.1/DER/DEREncodable.swift
- ios/SecuritySdk/Classes/ASN.1/DER/DERIA5String.swift
- ios/SecuritySdk/Classes/ASN.1/DER/DERInteger.swift
- ios/SecuritySdk/Classes/ASN.1/DER/DERNull.swift
- ios/SecuritySdk/Classes/ASN.1/DER/DERObjectIdentifier.swift
- ios/SecuritySdk/Classes/ASN.1/DER/DEROctetString.swift
- ios/SecuritySdk/Classes/ASN.1/DER/DERPrintableString.swift
- ios/SecuritySdk/Classes/ASN.1/DER/DERSequence.swift
- ios/SecuritySdk/Classes/ASN.1/DER/DERSet.swift
- ios/SecuritySdk/Classes/ASN.1/DER/DERUTCTime.swift
- ios/SecuritySdk/Classes/ASN.1/DER/DERUTF8String.swift
This PR introduces ASN.1 types with DER (Distinguished Encoding Rules) encodables that serve as the building blocks for future work on PKCS related formats that require DER encoded octets.
> Implement ASN.1 types as DER encodables

- ios/Example/Tests/SecureEnclaveDigitalSignatureKeyManagerTests.swift
- ios/SecuritySdk/Classes/CryptographicKey.swift
- ios/SecuritySdk/Classes/Digital Signature/Secure Enclave/SecureEnclaveVerifyingKey.swift
This PR exposes a convenience method for PublicKey types to be able to export its material as an external representation and encoded appropriately depending on is algorithm type.
> Allow public key to be exportable

- ios/Example/Tests/SecureEnclaveDigitalSignatureKeyManagerTests.swift
- ios/SecuritySdk/Classes/CryptographicKey.swift
- ios/SecuritySdk/Classes/Digital Signature/DigitalSignatureKeyManager.swift
- ios/SecuritySdk/Classes/Digital Signature/DigitalSignatureSigner.swift
- ios/SecuritySdk/Classes/Digital Signature/DigitalSignatureVerifier.swift
- ios/SecuritySdk/Classes/Digital Signature/Secure Enclave/SecureEnclaveDigitalSignatureKeyManager.swift
- ios/SecuritySdk/Classes/Digital Signature/Secure Enclave/SecureEnclaveSigningKey.swift
- ios/SecuritySdk/Classes/Digital Signature/Secure Enclave/SecureEnclaveVerifyingKey.swift
This hides away the key abstraction and surfaces two protocols to perform the signing and verification operations.
> Hide key abstration away with signer and verifier protocols

- ios/Example/Tests/SecureEnclaveDigitalSignatureKeyManagerTests.swift
- ios/SecuritySdk/Classes/ASN.1/DER/DEREncodable.swift
- ios/SecuritySdk/Classes/CryptographicKey.swift
- ios/SecuritySdk/Classes/Digital Signature/ContentSigner.swift
- ios/SecuritySdk/Classes/Digital Signature/DigitalSignature.swift
- ios/SecuritySdk/Classes/Digital Signature/DigitalSignatureKeyManager.swift
- ios/SecuritySdk/Classes/Digital Signature/DigitalSignatureSigner.swift
- ios/SecuritySdk/Classes/Digital Signature/Secure Enclave/SecureEnclaveDigitalSignatureKeyManager.swift
- ios/SecuritySdk/Classes/Digital Signature/Secure Enclave/SecureEnclaveKeychainQueries.swift
- ios/SecuritySdk/Classes/Digital Signature/Secure Enclave/SecureEnclaveSigningKey.swift
- ios/SecuritySdk/Classes/Digital Signature/Secure Enclave/SecureEnclaveVerifyingKey.swift
- ios/SecuritySdk/Classes/Digital Signature/SigningPublicKey.swift
- ios/SecuritySdk/Classes/EllipticCurve.swift
- ios/SecuritySdk/Classes/KeyType.swift
- ios/SecuritySdk/Classes/SigningAlgorithm.swift
In order to reduce the scope of access to the raw keypairs, the `sign` method returns a new higher abstraction for `DigitalSignature` that provides the context of the signing algorithm along with the signature data.  An extended protocol `ContentSigner` which extends the protocol `DigitalSignatureSigner` to surface the public key `SigningPublicKey` when appropriate.
> Surface higher abstractions for digital signature and public key

- jvm/src/main/kotlin/app/cash/security_sdk/internal/TrifleAlgorithmIdentifier.kt
- jvm/src/main/kotlin/app/cash/security_sdk/internal/providers/BCContentVerifierProvider.kt
- jvm/src/main/kotlin/app/cash/security_sdk/internal/providers/TinkContentVerifierProvider.kt
- jvm/src/test/kotlin/app/cash/security_sdk/CertificateUtilTest.kt
- jvm/src/test/kotlin/app/cash/security_sdk/internal/providers/BCContentVerifierProviderTest.kt
- jvm/src/test/kotlin/app/cash/security_sdk/internal/providers/TinkContentVerifierProviderTest.kt
- jvm/src/test/kotlin/app/cash/security_sdk/internal/util/TinkUtil.kt
A parallel implementation of `ContentVerifierProvider` that handles raw key types instead of Tink wrapped keyset handles . The provider uses BouncyCastle as a delegate provider.
> Implement BC content verifier for raw key types

- android/cash-security-s2dk/src/test/java/app/cash/security_sdk/LibraryVersionUnitTest.kt
- gradle.properties
This should kick off publication of the 0.1.1 release of the library, enabling clients to use recently added features. Library is still very much 'in development' (v0) and all APIs are subject to change in future versions.
> Remove SNAPSHOT from 0.1.1 release.

- android/cash-security-s2dk/src/test/java/app/cash/security_sdk/LibraryVersionUnitTest.kt
- gradle.properties
- jvm/src/main/kotlin/app/cash/s2dk/common/LibraryVersion.kt
- jvm/src/test/kotlin/app/cash/s2dk/common/LibraryVersionTest.kt
Update version number to next version following the 0.1.1 release, and make sure that the version is -SNAPSHOT to prevent its publishing to maven.
> Begin development on 0.1.2.

- jvm/src/main/kotlin/app/cash/security_sdk/CertificateUtil.kt
- jvm/src/test/kotlin/app/cash/security_sdk/CertificateUtilTest.kt
- jvm/src/test/kotlin/app/cash/security_sdk/internal/providers/BCContentVerifierProviderTest.kt
- jvm/src/test/kotlin/app/cash/security_sdk/internal/util/TestUtil.kt
This adds a test fixture for a PKCS10 csr generated with a raw p256 public key. The PR also adds a unit test to exercise the signature validation on both the CSR and the signed Certificate with a tink content signer.
> Add test fixture for pkcs10 csr with raw key

- ios/SecuritySdk/Classes/ASN.1/ASN1Attribute.swift
- ios/SecuritySdk/Classes/ASN.1/ASN1AttributeTypeValue.swift
- ios/SecuritySdk/Classes/ASN.1/ASN1BitString.swift
- ios/SecuritySdk/Classes/ASN.1/ASN1Boolean.swift
- ios/SecuritySdk/Classes/ASN.1/ASN1IA5String.swift
- ios/SecuritySdk/Classes/ASN.1/ASN1Integer.swift
- ios/SecuritySdk/Classes/ASN.1/ASN1Null.swift
- ios/SecuritySdk/Classes/ASN.1/ASN1ObjectIdentifier.swift
- ios/SecuritySdk/Classes/ASN.1/ASN1OctetString.swift
- ios/SecuritySdk/Classes/ASN.1/ASN1PrintableString.swift
- ios/SecuritySdk/Classes/ASN.1/ASN1Sequence.swift
- ios/SecuritySdk/Classes/ASN.1/ASN1Set.swift
- ios/SecuritySdk/Classes/ASN.1/ASN1Type.swift
- ios/SecuritySdk/Classes/ASN.1/ASN1UTCTime.swift
- ios/SecuritySdk/Classes/ASN.1/ASN1UTF8String.swift
- ios/SecuritySdk/Classes/ASN.1/DER/DEREncodable.swift
This PR introduces a sort priority to each implementing ASN.1 type. This is necessary when a tiebreaker is needed when the tag type is not sufficient. The value octets are instead used for comparison. However, this only applies to primitive types, when an ASN.1 type happens to be constructed (set and sequence), the priority is calculated as a sum of the priorities of its collection.
----
In reference to X.690:
```
11.6 Set-of components
The encodings of the component values of a set-of value shall appear in ascending order, the encodings being compared
as octet strings with the shorter components being padded at their trailing end with 0-octets. 
```
https://www.itu.int/ITU-T/studygroups/com17/languages/X.690-0207.pdf
> Add priority property to ASN1Type for sorting

- ios/Example/SecuritySdk.xcodeproj/project.pbxproj
- ios/Example/Tests/CertificateDecodableTest.swift
This PR adds unit tests in the iOS SDK to add confidence in the decodability of the certificates (issuer and device) from the JVM SDK.
> Add unit tests in iOS for certificate decodability generated by JVM code

- jvm/src/main/kotlin/app/cash/trifle/CertificateUtil.kt
When a root / CA certificate is minted by the library, there are 3 extensions that must be set in order for the chain of trust to be properly validated. These extensions include basic constraint, key usages, and subject key identifier. 
More information:
https://www.rfc-editor.org/rfc/rfc3280#section-4.2.1.2
https://www.rfc-editor.org/rfc/rfc3280#section-4.2.1.3
https://www.rfc-editor.org/rfc/rfc3280#section-4.2.1.10
> Add critical cert extensions for root certificate

- ios/Example/Tests/TrifleTests.swift
- ios/Trifle/Sources/Certificate/X509TrustManager.swift
- ios/Trifle/Sources/Trifle.swift
This PR implements verifyCertificate in the iOS SDK to validate a given leaf (device certificate) against the certificate chain and up to the root certificate.
> Implement verifyCertificate in iOS

- jvm/build.gradle.kts
- jvm/src/main/kotlin/app/cash/trifle/internal/signers/TinkContentSigner.kt
This PR upgrades tink to 1.7.0 which has the package path of TinkKey changed. Dependencies on Trifle that also pulls in Tink may not be compatible due to the classpath not matching. By changing the gradle build script to compile the binary interface, we avoid runtime issues in the future
> Upgrade tink to 1.7.0

- android/sample_app/src/main/java/app/cash/trifle/MainActivity.kt
- android/trifle/src/main/java/app/cash/trifle/KeyHandle.kt
The KeyHandle class is responsible for abstracting away key generation and use. Add the class, and corresponding key generation.
> Add KeyHandle class for Android SDK.

- android/trifle/build.gradle.kts
The jvm project contains APIs which should be common across Android and server Trifle use-cases.  Switching to api() enables them to be used directly on Android without needing a wrapper.
> Change android jvm gradle dependency to api from implementation.

- android/sample_app/build.gradle.kts
- android/trifle/build.gradle.kts
- android/trifle/src/main/java/app/cash/trifle/KeyHandle.kt
- gradle/libs.versions.toml
When deserializing, the instance of the keystore is instantiated but not initialized. In order to do so, the load function has to be called without any parameters. This will fix PR[#97](https://github.com/cashapp/trifle/pull/97).
> Load params to keystore

- android/trifle/src/main/java/app/cash/trifle/KeyHandle.kt
This can be used directly as part of our JCADelegate for signing.
> Expose KeyPair from Trifle KeyHandle.

- .github/workflows/gradle_build.yml
Hypothesis is that ubuntu-latest might be incompatible with action runner. Switching to macOS might resolve timeout issues: https://github.com/actions/runner-images/issues/6704
> Update platform to macOS for publish job

- Trifle.podspec
- ios/Trifle/Sources/Trifle.swift
This version introduces new Trifle APIs for checking key handle validity and deleting a key handle from the key chain.
> bump up iOS version to 0.2.1

- ios/Trifle/Sources/Digital Signature/Secure Enclave/SecureEnclaveKeychainQueries.swift
Fixes this warning about inferred types:
> ios/Trifle/Sources/Digital Signature/Secure Enclave/SecureEnclaveKeychainQueries.swift:41:34: warning: heterogeneous collection literal could only be inferred to '[CFString : Any]'; add explicit type annotation if this is intentional
> 
>```
>             kSecPrivateKeyAttrs: [
> ```
> Swift: Fix warning in Xcode 14.3

- android/trifle/build.gradle.kts
These dependencies are being included on projects that import Trifle, so we need to remove them.
> Remove unnecessary dependencies from Android implementation

- gradle/libs.versions.toml
- jvm/src/main/kotlin/app/cash/trifle/delegate/DelegateImpl.kt
The authority key identifier extension field may be used by the issuer and end entity to identify a signing certificate chain which is recommended in [RFC 3280](https://www.rfc-editor.org/rfc/rfc3280#section-4.2.1.2). 
The certificate authority will have the same key identifier for both the authority and subject key identifier fields.
The end entity will have its public key's checksum as the value of the subject key identifier field, but the issuer's subject key identifier as the value of its authority key identifier field.
---
Both the subject and authority key identifier fields should not be marked as critical
> Add authority key identifier extension

- android/trifle/build.gradle.kts
- android/trifle/src/androidTest/java/app/cash/trifle/KeyHandleTest.kt
- android/trifle/src/main/java/app/cash/trifle/KeyHandle.kt
Currently fails with:
```
java.security.KeyStoreException: Uninitialized keystore
at java.security.KeyStore.containsAlias(KeyStore.java:1312)
at app.cash.trifle.KeyHandle$Companion.deserialize(KeyHandle.kt:53)
at app.cash.trifle.KeyHandleTest.serializeDeserialize(KeyHandleTest.kt:10)
```
> Add an instrumentation test for KeyHandle

- jvm/src/main/kotlin/app/cash/trifle/Certificate.kt
- jvm/src/test/kotlin/app/cash/trifle/CertificateTests.kt
Check that the provided certificate matches the associated certificate chain and also that the certificate contains the same information as the passed-in certificate request.
> Add verify() method to the jvm certificate representation.

- jvm/src/main/kotlin/app/cash/trifle/Certificate.kt
- jvm/src/main/kotlin/app/cash/trifle/SignedData.kt
- jvm/src/main/kotlin/app/cash/trifle/internal/validators/CertChainValidatorFactory.kt
- jvm/src/main/kotlin/app/cash/trifle/internal/validators/X509CertChainValidator.kt
- jvm/src/test/kotlin/app/cash/trifle/CertificateTests.kt
- jvm/src/test/kotlin/app/cash/trifle/internal/validators/CertChainValidatorTests.kt
A simple boolean return value masks the underlying cause of the failure, which clients may wish to know in order to take appropriate corrective action. Expose this, and also expose an API for allowing the caller to specify the validity date, instead of relying purely on the system default.
> Change Certificate.verify() to include reason in response.

- jvm-testing/src/main/kotlin/app/cash/trifle/testing/TestCertificateAuthority.kt
- jvm/src/main/kotlin/app/cash/trifle/delegate/CertificateAuthorityDelegate.kt
- jvm/src/main/kotlin/app/cash/trifle/delegate/DelegateImpl.kt
- jvm/src/test/kotlin/app/cash/trifle/TrifleTest.kt
Currently cert generation uses Period which has the smallest granularity of days. Changing to Duration so it supports seconds if needed for testing.
> Support more granular cert creation TTLs

- android/trifle/src/test/java/app/cash/trifle/LibraryVersionUnitTest.kt
- gradle.properties
This version will increase the granularity of creating client certificates TTL.
> bump up jvm version to 0.2.4 for release

- android/sample_app/build.gradle.kts
- jvm-testing/build.gradle.kts
- jvm/build.gradle.kts
Updates tink dependency to 1.9.0 and update gradle build to use `implementation` instead of `api` to add tink to not leak tink dependency into other modules and only available to at runtime.
> Update tink to 1.9.0

- README.md
- ios/Example/Podfile.lock
- ios/Example/Tests/CertificateTests.swift
- ios/Example/Tests/TrifleTests.swift
- ios/Trifle/Sources/Trifle.swift
- ios/Trifle/Sources/TrifleCertificate.swift
As part of this PR:
- we create a generic TrifleError.securityFramework error which bubbles up the framework's error code to the calling app
- we remove the verify functionality from the createSignedData()
> Better visibility into verify errors

- jvm-testing/build.gradle.kts
- jvm/build.gradle.kts
Downgrade tink temporarily back to 1.7.0 to unblock builds that depend on the same transitive dependencies that was introduce in tink 1.9.0.
> Downgrade tink to 1.7.0 to temporarily fix Android integration issue

- jvm/src/main/kotlin/app/cash/trifle/SignedData.kt
- jvm/src/main/kotlin/app/cash/trifle/delegate/DelegateImpl.kt
- jvm/src/main/kotlin/app/cash/trifle/internal/Buffer.kt
- jvm/src/main/kotlin/app/cash/trifle/internal/signers/JCAContentSigner.kt
- jvm/src/main/kotlin/app/cash/trifle/internal/signers/TinkContentSigner.kt
- jvm/src/test/kotlin/app/cash/trifle/TrifleTest.kt
This PR introduces a new `Buffer` class that extends `ByteArrayOutputStream` to override the `reset` method. This properly clears out the underlying buffer used in the `ContentSigner` classes.
The PR also moves any usages of the buffer into an auto-closeable scope.
> Extend ByteArrayOutputStream with proper clearing of buffer

- android/trifle/src/androidTest/java/app/cash/trifle/LibraryVersionUnitTest.kt
- gradle.properties
This PR creates a release for 0.2.8. There are breaking changes introduced to the Android API. The changes can be found in #167 and the README has been updated to reflect the change.
> Update jvm/android release for 0.2.8

- jvm/src/main/kotlin/app/cash/trifle/internal/providers/JCAContentVerifierProvider.kt
- jvm/src/main/kotlin/app/cash/trifle/internal/providers/TrifleContentVerifierProvider.kt
`TrifleContentVerifierProvider` itself does not require storing of states. The PR re-defines the sealed class as a sealed interface instead.
> Re-define TrifleContentVerifierProvider as sealed interface

- jvm/src/main/kotlin/app/cash/trifle/CertificateRequest.kt
- jvm/src/main/kotlin/app/cash/trifle/SignedData.kt
- jvm/src/main/kotlin/app/cash/trifle/TrifleAlgorithmIdentifier.kt
- jvm/src/main/kotlin/app/cash/trifle/delegate/DelegateImpl.kt
- jvm/src/main/kotlin/app/cash/trifle/delegate/JCADelegate.kt
- jvm/src/main/kotlin/app/cash/trifle/delegate/TinkDelegate.kt
- jvm/src/main/kotlin/app/cash/trifle/internal/providers/TrifleContentVerifierProvider.kt
- jvm/src/main/kotlin/app/cash/trifle/providers/TrifleContentVerifierProvider.kt
- jvm/src/main/kotlin/app/cash/trifle/providers/jca/JCAContentVerifierProvider.kt
- jvm/src/main/kotlin/app/cash/trifle/signers/Buffer.kt
- jvm/src/main/kotlin/app/cash/trifle/signers/TrifleContentSigner.kt
- jvm/src/main/kotlin/app/cash/trifle/signers/jca/JCAContentSigner.kt
- jvm/src/main/kotlin/app/cash/trifle/signers/tink/TinkContentSigner.kt
- jvm/src/test/kotlin/app/cash/trifle/CertificateRequestTests.kt
- jvm/src/test/kotlin/app/cash/trifle/TrifleTest.kt
- jvm/src/test/kotlin/app/cash/trifle/providers/TrifleContentVerifierProviderTests.kt
- jvm/src/test/kotlin/app/cash/trifle/signers/TrifleContentSignerTests.kt
- jvm/src/test/kotlin/app/cash/trifle/signers/jca/JCAContentSignerTests.kt
- jvm/src/test/kotlin/app/cash/trifle/signers/tink/TinkContentSignerTests.kt
Rearrange organization of both content signer and provider classes to non-internal sub-packages and into their respective packages based on implementation.
> Remove internal subpackage(s) from content signers and providers

- android/sample_app/src/main/java/app/cash/trifle/MainActivity.kt
- android/trifle/src/androidTest/java/app/cash/trifle/KeyHandleTest.kt
- android/trifle/src/androidTest/java/app/cash/trifle/TrifleTest.kt
- android/trifle/src/main/java/app/cash/trifle/Trifle.kt
Rename Android API from TrifleApi to Trifle to keep consistency with class names with iOS implementation.
> Rename Android API class to Trifle

- android/trifle/src/androidTest/java/app/cash/trifle/LibraryVersionUnitTest.kt
- gradle.properties
- `jvm` package now splits into an additional `common` package
- `jvm` package only contains `tink` specific implementations, removing coupling of `tink` and `android` SDK
- `android` SDK no longer depend on the `jvm` package. Instead, it depends on a new `common` package
- Breaking changes to Android API due to renaming of the API class `TrifleApi` -> `Trfile` in order to keep class naming consistent across platforms
> Android release 0.2.9

- common/src/main/kotlin/app/cash/trifle/SignedData.kt
- common/src/test/kotlin/app/cash/trifle/TrifleTest.kt
This PR defaults toString methods to redact the data field as it might contain sensitive information. This PR also exposes a secondary method in the scenario that developers would want to print data in plaintext.
> Redact SignedData and EnvelopedData toString by default and expose helper methods for unredacted values

- .github/workflows/swift_build.yml
- .gitignore
- Package.resolved
- Package.swift
- Trifle.podspec
- ios/Example/Podfile.lock
Add's SPM support to Trifle. Primarily adds a `Package.swift` file and a relevant github action test to ensure it builds.
NOTE: i updated the spec and the Package.swift to specify Wire ~4.7 explicitly because Trifle does not seem to build with Write 4.8+
> Add Swift Package Manager support

- Package.resolved
- Package.swift
- Trifle.podspec
- ios/Example/Podfile
- ios/Example/Podfile.lock
- ios/Example/Tests/CertificateTests.swift
- ios/Trifle/Sources/Generated/Protos/Certificate.swift
- ios/Trifle/Sources/Generated/Protos/MobileCertificateRequest.swift
- ios/Trifle/Sources/Generated/Protos/MobileCertificateResponse.swift
- ios/Trifle/Sources/Generated/Protos/SignedData.swift
- ios/Trifle/Sources/Trifle.swift
Part 1 of an update to get Trifle on a more current version of Wire.  The 4.9.3 release is the last to support memberwise initializers (via `WIRE_INCLUDE_MEMBERWISE_INITIALIZER`), so it's a natural stopping point to update Trifle and projects that depend on it.  The checked-in Swift code was regenerated with 4.9.3.
Part 2 will follow this one and update to Wire 5.x
> Update to Wire 4.9.3
